// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: hello.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// 客户端流式 RPC
	ClientStreamPing(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientStreamPingClient, error)
	// 服务端流式 RPC
	ServerStreamPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (Greeter_ServerStreamPingClient, error)
	// 双向流式 RPC
	BothStreamPing(ctx context.Context, opts ...grpc.CallOption) (Greeter_BothStreamPingClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ClientStreamPing(ctx context.Context, opts ...grpc.CallOption) (Greeter_ClientStreamPingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/Greeter/ClientStreamPing", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterClientStreamPingClient{stream}
	return x, nil
}

type Greeter_ClientStreamPingClient interface {
	Send(*PingRequest) error
	CloseAndRecv() (*PingReply, error)
	grpc.ClientStream
}

type greeterClientStreamPingClient struct {
	grpc.ClientStream
}

func (x *greeterClientStreamPingClient) Send(m *PingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterClientStreamPingClient) CloseAndRecv() (*PingReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PingReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) ServerStreamPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (Greeter_ServerStreamPingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/Greeter/ServerStreamPing", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServerStreamPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_ServerStreamPingClient interface {
	Recv() (*PingReply, error)
	grpc.ClientStream
}

type greeterServerStreamPingClient struct {
	grpc.ClientStream
}

func (x *greeterServerStreamPingClient) Recv() (*PingReply, error) {
	m := new(PingReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) BothStreamPing(ctx context.Context, opts ...grpc.CallOption) (Greeter_BothStreamPingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/Greeter/BothStreamPing", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBothStreamPingClient{stream}
	return x, nil
}

type Greeter_BothStreamPingClient interface {
	Send(*PingRequest) error
	Recv() (*PingReply, error)
	grpc.ClientStream
}

type greeterBothStreamPingClient struct {
	grpc.ClientStream
}

func (x *greeterBothStreamPingClient) Send(m *PingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBothStreamPingClient) Recv() (*PingReply, error) {
	m := new(PingReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// 客户端流式 RPC
	ClientStreamPing(Greeter_ClientStreamPingServer) error
	// 服务端流式 RPC
	ServerStreamPing(*PingRequest, Greeter_ServerStreamPingServer) error
	// 双向流式 RPC
	BothStreamPing(Greeter_BothStreamPingServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) ClientStreamPing(Greeter_ClientStreamPingServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamPing not implemented")
}
func (UnimplementedGreeterServer) ServerStreamPing(*PingRequest, Greeter_ServerStreamPingServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamPing not implemented")
}
func (UnimplementedGreeterServer) BothStreamPing(Greeter_BothStreamPingServer) error {
	return status.Errorf(codes.Unimplemented, "method BothStreamPing not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ClientStreamPing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ClientStreamPing(&greeterClientStreamPingServer{stream})
}

type Greeter_ClientStreamPingServer interface {
	SendAndClose(*PingReply) error
	Recv() (*PingRequest, error)
	grpc.ServerStream
}

type greeterClientStreamPingServer struct {
	grpc.ServerStream
}

func (x *greeterClientStreamPingServer) SendAndClose(m *PingReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterClientStreamPingServer) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_ServerStreamPing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).ServerStreamPing(m, &greeterServerStreamPingServer{stream})
}

type Greeter_ServerStreamPingServer interface {
	Send(*PingReply) error
	grpc.ServerStream
}

type greeterServerStreamPingServer struct {
	grpc.ServerStream
}

func (x *greeterServerStreamPingServer) Send(m *PingReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_BothStreamPing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).BothStreamPing(&greeterBothStreamPingServer{stream})
}

type Greeter_BothStreamPingServer interface {
	Send(*PingReply) error
	Recv() (*PingRequest, error)
	grpc.ServerStream
}

type greeterBothStreamPingServer struct {
	grpc.ServerStream
}

func (x *greeterBothStreamPingServer) Send(m *PingReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBothStreamPingServer) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreamPing",
			Handler:       _Greeter_ClientStreamPing_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamPing",
			Handler:       _Greeter_ServerStreamPing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BothStreamPing",
			Handler:       _Greeter_BothStreamPing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
